### ISSUE TITLE
Copy-&-Paste error in com/com_messages.c, function disable_status_led()

### ISSUE THREAD

**Issue by khadoran** [Tinkerforge/bricklib#4]
The lines 121-123 contain the following code:

#ifdef LED_EXT_BLUE_1
	led_off(LED_EXT_BLUE_3);
#endif

It appears that the macro name passed to led_off() should be LED_EXT_BLUE_1 instead of LED_EXT_BLUE_3.

**Comment by borg42** [comment]
Indeed, thank you for pointing that out!
